version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data postgres


volumes:
  db:
